// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nwafdcrlhkemvyznrxlz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im53YWZkY3JsaGtlbXZ5em5yeGx6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcwMjcyMjMsImV4cCI6MjA2MjYwMzIyM30.lbzPTDVcI4cly5Im1-wPKy6tHEr_rUEJyb8MP0bnTU4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);